#ifndef _ELM327_H
#define _ELM327_H

// Generated by Codex (OpenAI), based on GPT-5. Model: terra/medium
// Generation context: ELM327 USB CDC to CAN/ISO-15765 translation for GiUCAN.

#include "stm32f0xx_hal.h"

// Largest command accepted by the CDC endpoint, including an optional CR.
#define ELM327_COMMAND_MTU 64

// A complete 64-byte ISO-TP reply with headers and spaces is 204 bytes.
#define ELM327_MTU 256

// Convert one received CAN frame to ELM text. A return value of zero means
// that the frame was consumed while assembling an ISO-TP response.
int16_t elm327_parse_frame(uint8_t *buf, CAN_RxHeaderTypeDef *frame_header,
        uint8_t *frame_data);
int8_t elm327_parse_str(uint8_t *buf, uint8_t len);
void elm327_init(void);
void elm327_process(void);

#endif // _ELM327_H
