 #ifndef INC_PRINTF_CONFIG_H_
 #define INC_PRINTF_CONFIG_H_
 
 #define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
 #define PRINTF_DEFAULT_FLOAT_PRECISION 3
 #define PRINTF_MAX_FLOAT 1e6
 #define PRINTF_DISABLE_SUPPORT_LONG_LONG
 #define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
 
 #endif /* INC_PRINTF_CONFIG_H_ */
