name: Build stable

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    name: GiUCAN stable
    runs-on: ubuntu-latest
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - run: arm-none-eabi-gcc --version

      - name: Clone
        uses: actions/checkout@v3

      - name: Compile C1CAN
        run: |
          CFLAGS='-DBUILD_VERSION=\"${{ github.ref_name }}\" -DC1CAN' make all
          mv build/GiUCAN*.elf GiUCAN_C1CAN.elf
                    
      - name: Compile BHCAN
        run: |
          CFLAGS='-DBUILD_VERSION=\"${{ github.ref_name }}\" -DBHCAN' make clean all
          mv build/GiUCAN*.elf GiUCAN_BHCAN.elf

      - name: Compile SLCAN
        run: |
          CFLAGS='-DBUILD_VERSION=\"${{ github.ref_name }}\" -DSLCAN' make clean all
          mv build/GiUCAN*.elf GiUCAN_SLCAN.elf
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          name: Stable diesel 7 inches TFT ${{ github.ref_name }}
          files: |
            ./GiUCAN_C1CAN.elf
            ./GiUCAN_BHCAN.elf
            ./GiUCAN_SLCAN.elf
